### ISSUE TITLE
Add bash + basic python lesson

### ISSUE THREAD

**Issue by chrisburr** [lhcb/starterkit-lessons#12]

**Comment by goi42** [comment]
On the schedule, Screen is listed as part of the intro to LHCb software lesson. This is a little out-of-step with what is otherwise a very coherent lesson. It's fine to include there, I think, but I wanted to double-check whether the bash instructors were thinking to include it.

**Comment by alexpearce** [comment]
Including screen as part of the bash lessons makes sense to me, if there's time.

**Comment by goi42** [comment]
I've done my teaching prep for it, so either way. I don't want to push it onto the bash people at the last minute.

**Comment by chrisburr** [comment]
I think this is covered by lhcb/analysis-essentials#16, lhcb/analysis-essentials#22, lhcb/analysis-essentials#23 and lhcb/analysis-essentials#25.

At this point in time I don't see much to gain from having our own bash lesson (or fork of [shell-novice](https://swcarpentry.github.io/shell-novice/)). It definitely won't be done for this year so any discussion can be done in a separate issue on [analysis-essentials](https://github.com/lhcb/analysis-essentials/pull/16).
