### ISSUE TITLE
Discuss DTF_FUN functors

### ISSUE THREAD

**Issue by alexpearce** [lhcb/starterkit-lessons#148]
In #144 we realised that we don't mention the `DTF_FUN` functor. This is a powerful way to use DecayTreeFitter, and is more explicit than `TupleToolDecayTreeFitter`. One can be more fine-grained with what's saved as well, which is nice.

We should mention it somewhere.

**Comment by vlisovsk** [comment]
@chrisburr @andriiusachov as you are teaching the DTF lesson this year, it might be worth updating the lessons with the DTF_FUN discussion.

**Comment by andriiusachov** [comment]
I will run the lesson tomorrow, so I will be able to add example of DTF_FUN usage
