### ISSUE TITLE
Remove(/redirect) old versions of the lessons

### ISSUE THREAD

**Issue by chrisburr** [lhcb/starterkit-lessons#15]

**Comment by alexpearce** [comment]
The migration for first-analys-steps is complete (lhcb/first-analysis-steps#240 and lhcb/first-analysis-steps#241), but not for [second-analysis-steps](https://github.com/lhcb/second-analysis-steps).

I guess there was a bit of manual fiddling for first-steps @chrisburr? This isn't a priority atm anyway.

**Comment by chrisburr** [comment]
Completed with lhcb/second-analysis-steps#56 and lhcb/second-analysis-steps#57.
