### ISSUE TITLE
Add EventPreFilters to DaVinci file running on grid

### ISSUE THREAD

**Issue by saschastahl** [lhcb/starterkit-lessons#17]
I think it would be good to teach students as quickly as possible that they can use EventPreFilters to make their jobs faster (and use fewer resources). It could be mentioned in a callout box at the end of the minimal DaVinci script lesson.

**Comment by alexpearce** [comment]
+1 billion.

**Comment by vlisovsk** [comment]
I can add an example of EventPrefilters doing the `HLT_PASS_RE('StrippingD2hhPromptDst2D2KKLineDecision')` which is probably the simplest thing to show. Then we may ask students to check the timing table and identify whether it runs faster with or without the filter. 

The question is which lesson to put this into. Is the [minimal DV job](https://lhcb.github.io/starterkit-lessons/first-analysis-steps/minimal-dv-job.html) an appropriate place? Or one of the consequent lessons?

**Comment by saschastahl** [comment]
Thanks, that is what I had in mind. I think the minimal DV job should be fine.

**Comment by alexpearce** [comment]
Hmm, ideally "minimal" wouldn't get any more complication, but I can't think of a better place other than a new lesson.

Let's try it there. Perhaps after this paragraph:

> In order to run an algorithm that we have previously created, we need to add it to the `UserAlgorithms` list. The `TupleFile` attribute defines the name of the ROOT output file that DaVinci will store any algorithm output in, which should be our ntuple.
