### ISSUE TITLE
Broken links to code

### ISSUE THREAD

**Issue by chrisburr** [lhcb/starterkit-lessons#180]
Some of links to the example code are broken.

Example: https://lhcb.github.io/starterkit-lessons/first-analysis-steps/code/add-tupletools/code/add-tupletools/ntuple_options.py
The right one being: https://lhcb.github.io/starterkit-lessons/first-analysis-steps/code/add-tupletools/ntuple_options.py

Reported by Giampi

**Comment by vlisovsk** [comment]
Hmm, I went through the pages quickly and cannot confirm the issue, for me all the links seem to work (probably I missed some?).

**Comment by chrisburr** [comment]
I think it's a GitBook bug, I can reproduce it with firefox on [first-analysis-steps/add-tupletools](https://lhcb.github.io/starterkit-lessons/first-analysis-steps/add-tupletools.html) by rapidly clicking `The updated options can be found here.`.

[This solution works](https://github.com/GitbookIO/gitbook/issues/1539#issuecomment-392027824). i.e. replacing:

```bash
<a href="code/add-tupletools/ntuple_options.py">here</a>
```

with:

```bash
<a href="code/add-tupletools/ntuple_options.py" download target="_blank">here</a>
```

I can think of two options for implementing this:
 * Use the HTML syntax instead of markdown everywhere we want a link
 * Run an processing step after running gitbook build using something like:

```bash
sed -i --regexp-extended 's#(<a href=".*\.py")>#\1 download target="_blank">#g' build/**/*.html
```

**Comment by vlisovsk** [comment]
But does it work for you if you do right-click -> open in a new tab?

**Comment by chrisburr** [comment]
It does, provided I don't left click the link multiple times first (it causes the URL bar to change).

**Comment by vlisovsk** [comment]
I guess this is fixed now?

**Comment by chrisburr** [comment]
It should be :tada:
