### ISSUE TITLE
Link has changed

### ISSUE THREAD

**Issue by alibenn** [lhcb/starterkit-lessons#191]
In this page
https://lhcb.github.io/starterkit-lessons/second-analysis-steps/simulation.html
there is a link to
http://cloud.e5.physik.tu-dortmund.de/eventtype/
which is broken.
The new location is:
http://lbeventtype.web.cern.ch/

**Comment by alexpearce** [comment]
Thanks for reporting!

Would you willing to fix this with a pull request?

**Comment by chrisburr** [comment]
Fixed in #192
