### ISSUE TITLE
Problem with running Bender

### ISSUE THREAD

**Issue by marthaisabelhilton** [lhcb/starterkit-lessons#194]
When trying to run the Bender command:
`lb-run Bender/latest bender 00070793_00000001_7.AllStreams.dst`
I get the following error about setting `DataType`:
`# BenderTools.DstExplorer   ERROR   DataType is not defined yet`
and
`TypeError: You must set DataType`

**Comment by alexpearce** [comment]
The data type is indeed needed to run an application. Bender tries to deduce this, e.g. for you give it an LFN it will parse the path to find a year, but with a 'bare' local DST it has nothing to go on.

I think you can specify the datatype with the `-y/--year` flag.

**Comment by marthaisabelhilton** [comment]
Ok I think the flag is `-d` I've made a change in the lessons now.
