### ISSUE TITLE
Bug in Interactively exploring a DST

### ISSUE THREAD

**Issue by GerwinMeier** [lhcb/starterkit-lessons#213]
Hi,
I think there is a bug in **Interactively exploring a DST**. In the function `advance(decision)` you run over 10000 events to look, if there is any event, which fulfil the requirements of a stripping line. However you always look into the first event. So I think, the command `appMgr.run(1)` should be `appMgr.run(n)`.
It would be great, if someone could check that.
Thanks

**Comment by laurentdufour** [comment]
`appMgr.run(1)` actually advances 1 event further in the file, so it should be correct. Why do you think it is wrong? Do you see unexpected output?

**Comment by GerwinMeier** [comment]
I had, but after I started a fresh interactive session for the dst to test the function once more, everything works as expected. Probably I have redefined something before. So there is no bug at all.
Sorry for the noise.
