### ISSUE TITLE
Remove installation of anaconda

### ISSUE THREAD

**Issue by goi42** [lhcb/starterkit-lessons#22]
Anaconda installation as described seems to take _O_(3 GB). This is an obscene amount of space in general, but especially on a home directory on lxplus (max of 10 GB). Is this installation really necessary? Unless I installed anaconda a long time ago and forgot about it, it doesn't seem necessary for coding python on lxplus, which can already run ipython...

**Comment by alexpearce** [comment]
> Is this installation really necessary?

No, I don't think so. The LCG stack provides everything that we need, including modules like numpy and matplotlib.

**Comment by apuignav** [comment]
Is git modern enough? I remember it was one of the concerns...

**Comment by alexpearce** [comment]
A pretty recent git ships with LbScripts now.

```shell
$ which -a git
/cvmfs/lhcb.cern.ch/lib/lhcb/LBSCRIPTS/LBSCRIPTS_v9r1p7/InstallArea/scripts/git
/usr/bin/git
$ git --version
git version 2.14.2
```

(Actually it's _the_ latest version; I don't know if that will last for long, but it's good enough whatever.)

We used to build git on lxplus during the lessons, but even I don't bother with it anymore.

**Comment by apuignav** [comment]
Then I don't see any reason no to remove anaconda :-)

**Comment by goi42** [comment]
> Actually it's _the_ latest version
It appears v2.15.0-rc1 is actually more recent--but I was going to suggest removing the git installation step as well...
I'll remove both of these in my fork and make a pull request soon.
