### ISSUE TITLE
Add analysis productions

### ISSUE THREAD

**Issue by Dylan-JW** [lhcb/starterkit-lessons#225]
There is currently no mention of the analysis productions system (originally the [(charm) working group productions](https://gitlab.cern.ch/lhcb-datapkg/WG/CharmWGProd)). Since this is hopefully going to be widely used, I think it would be a good idea to give people an introduction to the system.

My initial ideas for how this lesson could look is to start with a simple walkthrough of a local production: cloning the repo, adding options & info .json/.yaml files, then running local tests and looking at the output .root file. Following this, there could be a look at the new monitoring page for analysis productions, and how to find the tuples, logs, and options from existing productions.

N.B. I'm happy to draft this lesson myself, if this is something that people think would be useful. If so, would this fit best in the self-guided lessons, or in the first/second analysis sections?

**Comment by alexpearce** [comment]
This feels like a more natural fit for the self-guided lessons. It's certainly a topic I'd be happy to see people becoming familiar with.

But perhaps this sort of documentation would be better living closer to the WG productions source code. Then there's less chance of the tutorial drifting away from the current workings (hopefully). Thoughts @cburr?

**Comment by Dylan-JW** [comment]
(I think you tagged the wrong account for Chris by mistake - @chrisburr)

I agree that creating a tutorial for this separate from the source code risks it becoming outdated if things change in future. Also the existing documentations for the WG productions is already quite good.

However, for at least a part of the analysis production process, personally I am of the opinion that the added benefit to new collaboration members of having a step-by-step tutorial outweighs those risks. The StarterKit is already full of similar walkthrough-style lessons - in my experience, that's a big part of what makes them so helpful for people. Exactly which parts would work best in such a lesson is definitely a discussion worth having before proceeding.

**Comment by eduardo-rodrigues** [comment]
In DPA we only briefly talked about documentation (some already available at http://lhcb-dpa.web.cern.ch/lhcb-dpa/ for a couple of WPs) hence a proper discussion is indeed needed. To be honest my first impression is that analysis productions are a bit outside the general scope of the Starterkit; it might make more sense to have the doc close to the code, hence in the DPA doc. But again, happy to discuss, and @chrisburr should comment first.

**Comment by Dylan-JW** [comment]
Reviving this now that documentation has been added to the AP Gitlab page - it seems to me to be very thorough, and includes examples for pretty much all steps of making a new AP. Perhaps given this there is less of a need for a starterkit lesson?

**Comment by chrisburr** [comment]
Hi all, sorry for the delay. I think one of the aims of the Starterkit should be to show people the preferred way of doing an analysis and therefore it would be useful to dedicate some time at the Starterkit demonstrating how to submit analysis productions. Adding it either before/after the Ganaga lessons would probably make the most sense, with the conclusion that WG/Analysis Productions should be preferred for cases where you don't need the flexibility that Ganga provides.

Ultimately its up to the people that are organising/teaching this year to decide what should be updated in preparation for Run 3 and what should wait until future kits.

**Comment by alexpearce** [comment]
I think we can close this given #228 is in.
