### ISSUE TITLE
Add link to Run2OperationSummary twiki

### ISSUE THREAD

**Issue by rmatev** [lhcb/starterkit-lessons#254]
We should probably add a link to https://twiki.cern.ch/twiki/bin/viewauth/LHCbInternal/Run2OperationSummary, which is the canonical place for listing know issues with the Run 2 data, and is potentially interesting for analysts. Where is this best done?

**Comment by alexpearce** [comment]
I'd say "Asking good questions" could work (as this page can help answer "what could be/is wrong with my data?") or perhaps "Changes to the data flow in Run 2".
