### ISSUE TITLE
Create few issues to solve during the Friday lesson?

### ISSUE THREAD

**Issue by vlisovsk** [lhcb/starterkit-lessons#34]
On Friday, one of the goals of the lesson is to teach students to create their own issues here and to solve those already existing. As an easy start, it would be nice to have some *simple* issues prepared so that they can be solved during the lesson.

If you have any ideas for that, it would be great to prepare them in advance, and mark by 'Friday lesson' label, so that we don't touch these issues until Friday.

**Comment by alexpearce** [comment]
We have thought of this 😁 In the original repo, first-analysis-steps, we assigned the [easy label to some issues](https://github.com/lhcb/first-analysis-steps/labels/Easy) that we thought would be good for first-timers. Some of these issues might be out-dated now, but it should be a good start.

**Comment by vlisovsk** [comment]
Great! Should I copy some of them here to make things simpler?

**Comment by alexpearce** [comment]
Yes it’s probably easier if we do that (I did look into properly transferring them, but GotHub doesn’t support it).

**Comment by vbellee** [comment]
Also, should we create the "Friday lesson" label also in Analysis Essentials?

**Comment by alexpearce** [comment]
Yep! I think “Easy” makes more sense for both repos, though.

**Comment by vbellee** [comment]
I created an "Easy" label for both repos.

**Comment by vlisovsk** [comment]
So, I copied few of old issues (with links pointing to the originals), and added couple of new (mainly about the fact that we migrated from D->Kpi to D->KK, which was not reflected in certain not-very-important places).

I propose to leave this as it is, so that we have something *really* easy to solve during the lesson.
(And everyone is invited to search for additional little bugs!)

**Comment by chrisburr** [comment]
I'm going to close this seeming as the Starterkit is (very) finished, we can have a new issue for next year.
