### ISSUE TITLE
lhcb-proxy-init?

### ISSUE THREAD

**Issue by vlisovsk** [lhcb/starterkit-lessons#53]
Should we tell people to run `lhcb-proxy-init` command before launching ganga?
Or it is enough that ganga requests the password itself at some point?

**Comment by alexpearce** [comment]
We do [mention `lhcb-proxy-init`](https://lhcb.github.io/starterkit-lessons/first-analysis-steps/files-from-grid.html). Given that Ganga should renew your proxy for you, I don't think its necessary to mention `lhcb-proxy-init` again explicitly.
