### ISSUE TITLE
Configure DaVinci that the data is simulated to get rid of some errors

### ISSUE THREAD

**Issue by roelaaij** [lhcb/starterkit-lessons#56]
The [interactive-dst](https://github.com/lhcb/starterkit-lessons/blob/master/first-analysis-steps/interactive-dst.md) lesson is run on simulated data, but `DaVinci` is not told about this so you see errors like:
```RunStampCheck       ERROR Database not up-to-date. No valid data for run 6251347 at 1970-01-01 00:00:00.0 UTC```

**Comment by goi42** [comment]
resolved: pull request #46
