### ISSUE TITLE
LaTeX not working

### ISSUE THREAD

**Issue by kdungs** [lhcb/starterkit-lessons#6]
**This 💩 is so 🔥.**  For real folks! It's really impressive how you continue to do such awesome work and make the Starterkit better every day!

That being said, LaTeX integration (e.g. [here, bottom of the page (screenshot below)](https://lhcb.github.io/starterkit-lessons/second-analysis-steps/tistos-diy.html)) does not seem to work.

<img width="791" alt="screen shot 2017-05-09 at 19 06 52" src="https://cloud.githubusercontent.com/assets/891877/25863088/b64e2e38-34ea-11e7-8c3f-f435e121cfc1.png">

**Comment by apuignav** [comment]
It's working for me. Can you recheck?

**Comment by kdungs** [comment]
Weird, it's working now. Sorry for the noise :(
