### ISSUE TITLE
Add lesson about the use of database tags

### ISSUE THREAD

**Issue by saschastahl** [lhcb/starterkit-lessons#72]
Using and finding the right database tags is often not very intuitive. And it also depends on the use case, what the recommended way is. E.g. in MC you should always use the one used in the generation while in data the latest one is often but not always preferred.
There are some twiki pages containing information but they look a bit outdated.
E.g. this one:
https://twiki.cern.ch/twiki/bin/view/LHCb/RecommendedTags

**Comment by alexpearce** [comment]
This was suggested in the Starterkit debriefing. We thought it would be good to have a page that covers DB tags and DaVinci versions, because they both have a similar "what version should I use" problem.

**Comment by saschastahl** [comment]
Ah very good.

**Comment by mesmith75** [comment]
Might be nice to mention the helpful feature in ganga?

**Comment by vlisovsk** [comment]
Partially solved in #152. I admit we can provide more details in a different place.
