### ISSUE TITLE
ImpactKit 2018 - Project ideas

### ISSUE THREAD

**Issue by chrisburr** [lhcb/starterkit-lessons#76]
This issue is for keeping track of project ideas for the next ImpactKit. There doesn't need to be any additional details, just enough words to make sure so we don't forget them.

(Though information/links/contact people/etc. are also welcome!)

My ideas:
- Correcting the magnetic field map
- Adding pdfs to RooFit (Hypatia, Triple Gaussian, ...)
- Write some self guided lessons (scikit-learn, fitting, limit setting with CLs)

**Comment by seneubert** [comment]
We could also add some advanced AP lessons:
  * Container customization
  * Snakemake wildcarding

**Comment by apuignav** [comment]
@sneubert After talking to some Luca yesterday, I  was thinking to have a lesson on "How to containerize your analysis" and then add as project "Containerize your analysis". However, I would not put advanced AP lessons in the ImpactKit: normal lessons would be enough, as people don't know much about it anyway... What do you think?
