### ISSUE TITLE
Exercise in "The simulation framework" not working out of the box

### ISSUE THREAD

**Issue by dovombru** [lhcb/starterkit-lessons#81]
When following the instructions for "Setting up a new Decay" in "The simulation framework" lesson of the second analysis steps, the .run command gives the following error:
./run: line 21: ./build_env.sh: No such file or directory

When following these instructions for testing decay files, the environment is setup properly and the execution of the example provided there works:
https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/blob/master/CONTRIBUTING.md

The problem seems to come from the difference between cmt (SetupProject) and lb-dev. Since I'm no expert, I'm not sure how to fix the tutorial. 

I tried running the tutorial by setting up the everything following the SetupProject steps (v49r9), but when creating the xgen file, one more option is needed: $GAUSSOPTS/Gauss-2016.py, as in the example on https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/blob/master/CONTRIBUTING.md, otherwise the following error appears:
ToolSvc.EvtGenDecay       ERROR EvtGen Error from EvtGen
Unknown particle name:N(1440)+ on line 10787

This is the list of commands that worked for me:

SetupProject -c x86_64-slc6-gcc49-opt Gauss v49r9 --build-env
cd ~/cmtuser/Gauss_v49r9
SetupProject -c x86_64-slc6-gcc49-opt Gauss v49r9

git lb-clone-pkg  Gen/DecFiles 

cd ~/cmtuser/Gauss_v49r9/Gen/DecFiles/
make

SetupProject Gauss v49r9
cd ~/cmtuser/Gauss_v49r9
gaudirun.py Gauss-Job.py $GAUSSOPTS/Gauss-2016.py $GAUSSOPTS/GenStandAlone.py \
            $DECFILESROOT/options/11164001.py $LBPYTHIA8ROOT/options/Pythia8.py
(here, Gauss-Job.py is the one from the tutorial saved in the directory ~/cmtuser/Gauss_v49r9)

SetupProject DaVinci v41r0
gaudirun.py DaVinciOptions.py (changing the .xgen file name to the one I created)

**Comment by dominikmuller** [comment]
Indeed, the instructions here were written before the migration of all the data packages to git. I'll open a merge request as soon as I have the time.

**Comment by chrisburr** [comment]
Hopefully this is fixed by #100 thanks to @dominikmuller
